#---------------------------------#
#      environment configuration  #
#---------------------------------#
os: WMF 5
version: 1.1.{build}
install:
  - cinst -y pester --version 3.3.13
  - ps: Get-PackageProvider -name nuget -ForceBootStrap -Force

#---------------------------------#
#      build configuration        #
#---------------------------------#
build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

#---------------------------------#
#      deployment configuration   #
#---------------------------------#
# scripts to run before deployment
deploy_script:
  - ps: |
      # Creating project artifact
      $stagingDirectory = (Resolve-Path ..).Path
      $manifest = Join-Path $pwd "POSHOrigin_NetScaler.psd1"
      (Get-Content $manifest -Raw).Replace("1.1", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest
      $zipFilePath = Join-Path $stagingDirectory "$(Split-Path $pwd -Leaf).zip"
      Add-Type -assemblyname System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::CreateFromDirectory($pwd, $zipFilePath)

      @(
          # You can add other artifacts here
          $zipFilePath
      ) | % {
          Write-Host "Pushing package $_ as Appveyor artifact"
          Push-AppveyorArtifact $_
        }